// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: basic_books_queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBook = `-- name: InsertBook :one
INSERT INTO library_items (user_id, kind, title, author, description, language, publication_year, genres, rating, 
    ownership_status, reading_status, publication_status, current_chapter, total_chapters,
    read_at, cover_path, notes) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17) 
    RETURNING id, user_id, kind, title, author, description, language, publication_year, genres, rating, ownership_status, reading_status, publication_status, current_chapter, total_chapters, read_at, cover_path, notes, search_vector, created_at, updated_at
`

type InsertBookParams struct {
	UserID            int64              `json:"user_id"`
	Kind              string             `json:"kind"`
	Title             string             `json:"title"`
	Author            string             `json:"author"`
	Description       string             `json:"description"`
	Language          string             `json:"language"`
	PublicationYear   *int32             `json:"publication_year"`
	Genres            []string           `json:"genres"`
	Rating            pgtype.Numeric     `json:"rating"`
	OwnershipStatus   string             `json:"ownership_status"`
	ReadingStatus     string             `json:"reading_status"`
	PublicationStatus string             `json:"publication_status"`
	CurrentChapter    pgtype.Numeric     `json:"current_chapter"`
	TotalChapters     pgtype.Numeric     `json:"total_chapters"`
	ReadAt            pgtype.Timestamptz `json:"read_at"`
	CoverPath         string             `json:"cover_path"`
	Notes             string             `json:"notes"`
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (LibraryItem, error) {
	row := q.db.QueryRow(ctx, insertBook,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.Language,
		arg.PublicationYear,
		arg.Genres,
		arg.Rating,
		arg.OwnershipStatus,
		arg.ReadingStatus,
		arg.PublicationStatus,
		arg.CurrentChapter,
		arg.TotalChapters,
		arg.ReadAt,
		arg.CoverPath,
		arg.Notes,
	)
	var i LibraryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Language,
		&i.PublicationYear,
		&i.Genres,
		&i.Rating,
		&i.OwnershipStatus,
		&i.ReadingStatus,
		&i.PublicationStatus,
		&i.CurrentChapter,
		&i.TotalChapters,
		&i.ReadAt,
		&i.CoverPath,
		&i.Notes,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, email, password_hash, display_name) VALUES ($1,$2,$3,$4) RETURNING id, email, username, password_hash, display_name, created_at, updated_at
`

type InsertUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectBooksByUser = `-- name: SelectBooksByUser :many
SELECT id, user_id, kind, title, author, description, language, publication_year, genres, rating, ownership_status, reading_status, publication_status, current_chapter, total_chapters, read_at, cover_path, notes, search_vector, created_at, updated_at FROM library_items WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type SelectBooksByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) SelectBooksByUser(ctx context.Context, arg SelectBooksByUserParams) ([]LibraryItem, error) {
	rows, err := q.db.Query(ctx, selectBooksByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryItem
	for rows.Next() {
		var i LibraryItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Language,
			&i.PublicationYear,
			&i.Genres,
			&i.Rating,
			&i.OwnershipStatus,
			&i.ReadingStatus,
			&i.PublicationStatus,
			&i.CurrentChapter,
			&i.TotalChapters,
			&i.ReadAt,
			&i.CoverPath,
			&i.Notes,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectBooksByUserAndKind = `-- name: SelectBooksByUserAndKind :many
SELECT id, user_id, kind, title, author, description, language, publication_year, genres, rating, ownership_status, reading_status, publication_status, current_chapter, total_chapters, read_at, cover_path, notes, search_vector, created_at, updated_at FROM library_items WHERE user_id = $1 AND kind = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type SelectBooksByUserAndKindParams struct {
	UserID int64  `json:"user_id"`
	Kind   string `json:"kind"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) SelectBooksByUserAndKind(ctx context.Context, arg SelectBooksByUserAndKindParams) ([]LibraryItem, error) {
	rows, err := q.db.Query(ctx, selectBooksByUserAndKind,
		arg.UserID,
		arg.Kind,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryItem
	for rows.Next() {
		var i LibraryItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Language,
			&i.PublicationYear,
			&i.Genres,
			&i.Rating,
			&i.OwnershipStatus,
			&i.ReadingStatus,
			&i.PublicationStatus,
			&i.CurrentChapter,
			&i.TotalChapters,
			&i.ReadAt,
			&i.CoverPath,
			&i.Notes,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserByEmail = `-- name: SelectUserByEmail :one
SELECT id, email, username, password_hash, display_name, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectUserByID = `-- name: SelectUserByID :one
SELECT id, email, username, password_hash, display_name, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) SelectUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectUserByUsername = `-- name: SelectUserByUsername :one
SELECT id, email, username, password_hash, display_name, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) SelectUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLibraryItems = `-- name: UpdateLibraryItems :one
UPDATE library_items SET title = $3, author = $4, rating = $5, cover_path = COALESCE(NULLIF($6, ''), cover_path), read_at = $7, description = $8,
language = $9, genres = $10, ownership_status = $11, reading_status=$12, current_chapter = $13, total_chapters = $14, notes = $15,  updated_at = now() WHERE id = $1 AND user_id = $2 RETURNING id, user_id, kind, title, author, description, language, publication_year, genres, rating, ownership_status, reading_status, publication_status, current_chapter, total_chapters, read_at, cover_path, notes, search_vector, created_at, updated_at
`

type UpdateLibraryItemsParams struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	Title           string             `json:"title"`
	Author          string             `json:"author"`
	Rating          pgtype.Numeric     `json:"rating"`
	CoverPath       string             `json:"cover_path"`
	ReadAt          pgtype.Timestamptz `json:"read_at"`
	Description     string             `json:"description"`
	Language        string             `json:"language"`
	Genres          []string           `json:"genres"`
	OwnershipStatus string             `json:"ownership_status"`
	ReadingStatus   string             `json:"reading_status"`
	CurrentChapter  pgtype.Numeric     `json:"current_chapter"`
	TotalChapters   pgtype.Numeric     `json:"total_chapters"`
	Notes           string             `json:"notes"`
}

func (q *Queries) UpdateLibraryItems(ctx context.Context, arg UpdateLibraryItemsParams) (LibraryItem, error) {
	row := q.db.QueryRow(ctx, updateLibraryItems,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Author,
		arg.Rating,
		arg.CoverPath,
		arg.ReadAt,
		arg.Description,
		arg.Language,
		arg.Genres,
		arg.OwnershipStatus,
		arg.ReadingStatus,
		arg.CurrentChapter,
		arg.TotalChapters,
		arg.Notes,
	)
	var i LibraryItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Language,
		&i.PublicationYear,
		&i.Genres,
		&i.Rating,
		&i.OwnershipStatus,
		&i.ReadingStatus,
		&i.PublicationStatus,
		&i.CurrentChapter,
		&i.TotalChapters,
		&i.ReadAt,
		&i.CoverPath,
		&i.Notes,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
