// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: basic_books_queries.sql

package db

import (
	"context"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO users (username, email, password_hash, display_name) VALUES ($1,$2,$3,$4) RETURNING id, username, email, password_hash, display_name, created_at, updated_at
`

type InsertUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	DisplayName  string `json:"display_name"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectBooks = `-- name: SelectBooks :many
SELECT id, user_id, kind, title, author, description, language, publication_year, genres, rating, ownership_status, reading_status, publication_status, current_chapter, total_chapters, read_at, finished_at, cover_path, notes, search_vector, created_at, updated_at FROM library_items ORDER BY created_at LIMIT $1 OFFSET $2
`

type SelectBooksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) SelectBooks(ctx context.Context, arg SelectBooksParams) ([]LibraryItem, error) {
	rows, err := q.db.Query(ctx, selectBooks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryItem
	for rows.Next() {
		var i LibraryItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.Language,
			&i.PublicationYear,
			&i.Genres,
			&i.Rating,
			&i.OwnershipStatus,
			&i.ReadingStatus,
			&i.PublicationStatus,
			&i.CurrentChapter,
			&i.TotalChapters,
			&i.ReadAt,
			&i.FinishedAt,
			&i.CoverPath,
			&i.Notes,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
