// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ImportedFile struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	LibraryItemID    *int64             `json:"library_item_id"`
	OriginalFileName string             `json:"original_file_name"`
	StoredFileName   string             `json:"stored_file_name"`
	FilePath         string             `json:"file_path"`
	MediaType        string             `json:"media_type"`
	Format           string             `json:"format"`
	SizeBytes        int64              `json:"size_bytes"`
	Sha256           string             `json:"sha256"`
	ImportedAt       pgtype.Timestamptz `json:"imported_at"`
}

type LibraryItem struct {
	ID                int64              `json:"id"`
	UserID            int64              `json:"user_id"`
	Kind              string             `json:"kind"`
	Title             string             `json:"title"`
	Author            string             `json:"author"`
	Description       string             `json:"description"`
	Language          string             `json:"language"`
	PublicationYear   *int32             `json:"publication_year"`
	Genres            []string           `json:"genres"`
	Rating            pgtype.Numeric     `json:"rating"`
	OwnershipStatus   string             `json:"ownership_status"`
	ReadingStatus     string             `json:"reading_status"`
	PublicationStatus string             `json:"publication_status"`
	CurrentChapter    pgtype.Numeric     `json:"current_chapter"`
	TotalChapters     pgtype.Numeric     `json:"total_chapters"`
	ReadAt            pgtype.Timestamptz `json:"read_at"`
	CoverPath         string             `json:"cover_path"`
	Notes             string             `json:"notes"`
	SearchVector      interface{}        `json:"search_vector"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
