// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_queries.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, hash) VALUES ($1,$2) RETURNING id, user_id, hash, created_at, expires_at
`

type CreateSessionParams struct {
	UserID int64   `json:"user_id"`
	Hash   *string `json:"hash"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.Hash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :one
DELETE FROM sessions WHERE expires_at < NOW() RETURNING id, user_id, hash, created_at, expires_at
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (Session, error) {
	row := q.db.QueryRow(ctx, deleteExpiredSessions)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :one
DELETE FROM sessions WHERE hash = $1 RETURNING id, user_id, hash, created_at, expires_at
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, hash *string) (Session, error) {
	row := q.db.QueryRow(ctx, deleteSessionByTokenHash, hash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteSessionByUserID = `-- name: DeleteSessionByUserID :many
DELETE FROM sessions WHERE user_id = $1 RETURNING id, user_id, hash, created_at, expires_at
`

func (q *Queries) DeleteSessionByUserID(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.Query(ctx, deleteSessionByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hash,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT id, user_id, hash, created_at, expires_at FROM sessions WHERE hash = $1
`

func (q *Queries) FindSessionByTokenHash(ctx context.Context, hash *string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHash, hash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hash,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
