---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librorum
  namespace: librorum
  labels:
    app: librorum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librorum
  template:
    metadata:
      labels:
        app: librorum
    spec:
      imagePullSecrets:
        - name: ghcr-pull

      containers:
        - name: librorum
          image: librorum-image
          imagePullPolicy: Always
          resources:
            requests:
              memory: "12Mi"
              cpu: "2m"
          ports:
            - name: web
              containerPort: 4545
              protocol: TCP
          envFrom:
            - configMapRef:
                name: librorum-config
            - secretRef:
                name: librorum-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 4545
          livenessProbe:
            httpGet:
              path: /
              port: 4545
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
