---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: librorum

resources:
  - namespace.yaml
  - configMap.yaml
  - go-deployment.yaml
  - go-service.yaml
  - ingress.yaml
  - postgres.yaml

images:
  - name: librorum-image
    newName: ghcr.io/yerrincar/librorum
    newTag: v0.1.2
